server:
  port: 20262
spring:
  application:
    name: account-query-service
  config:
    import: optional:configserver:http://localhost:8888
  profiles:
    active: dev

  liquibase:
    enabled: true
    driver-class-name: org.postgresql.Driver
    change-log: classpath:/db/changelog/db.changelog.master.yaml
    url: jdbc:postgresql://localhost:16851/db_account_query
    user: itpusr
    password: itp@168
  r2dbc:
    url: r2dbc:postgresql://localhost:16851/db_account_query
    username: itpusr
    password: itp@168

eureka:
  instance:
    instance-id: ${spring.application.name}
    prefer-ip-address: true

axon:
  axonserver:
    enabled: false
  kafka:
    bootstrap-servers: localhost:29092,localhost:29094,localhost:29096
    default-topic: Axon.AccountCQRS.Events
    client-id: kafka-axon-account-query
    message-converter-mode: default # alternative is cloud_event <https://cloudevents.io/>
    properties:
      security.protocol: PLAINTEXT # PLAINTEXT for no security purpose
    consumer:
      event-processor-mode: pooled_streaming
  serializer:
    general: jackson
    events: jackson
    messages: jackson